#!/usr/bin/osascript -l JavaScript

photos = Application('Photos');
photos.includeStandardAdditions = true;
photos.activate();
item = photos.selection()[0];
details = {"location": item.location(), "date": item.date()};
photos.setTheClipboardTo(JSON.stringify(details));
