#!/usr/bin/osascript -l JavaScript

photos = Application('Photos');
photos.includeStandardAdditions = true;
photos.activate();
var selection = photos.selection()
for (var i = 0; i < selection.length; i++) {
	var item = photos.selection()[i];
	details = JSON.parse(photos.theClipboard());
    item.date = new Date(details["date"]);
}
